### ISSUE TITLE
Update home page Friday night to promote conference schedule

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#166]
Could we please push the following items to the home page the evening of Friday the 21st?

1 – Update the white Method + Madness box to say the following (on all screen sizes):

**Headline:** Method + Madness is on!
**Subhead:** Enjoy over a dozen keynote speakers and choose between 6 breakout tracks.
**Button:** See the M+M Program (link to http://phxdw.com/mm-program/)

2 – Add a mobile Alert that says the following:

**Headline:** Method + Madness is on!
**Button:** View the M+M Program (link to http://phxdw.com/mm-program/)

I'm thinking this is just a white overlay – probably formatted similarly to the white box that we're modifying in the first request.

Is this doable?

**Comment by mattada** [comment]
Because the major headline change on part 1, I don't think #2 is needed at all anymore. 

Here it is phone sized with just part 1. 
http://factor1.me/2016/phxdw/
![screen shot 2016-10-20 at 12 58 51 pm](https://cloud.githubusercontent.com/assets/10223806/19575750/0da3a1aa-96c5-11e6-9515-1b4953e192c9.png)
